### ISSUE TITLE
CircleCI error "Error deleting container: Error response from daemon: Driver btrfs failed to remove root filesystem"

### ISSUE THREAD

**Issue by jpjoao** [herdphp/docker-phpqa#36]
It is a known issue on CircleCI (https://circleci.com/docs/1.0/docker-btrfs-error/), and has an easy solution:

> Normally, this is a red-herring and doesn’t affect your builds, so you can simply ignore it. You can add the `--rm=false` flag to `docker build` to avoid seeing this issue.

Should we adopt the solution or ignore the error?

**Comment by brunoric** [comment]
I'm ok with adopting the solution.

**Comment by jpjoao** [comment]
Adding `--rm=false` was not enough. I am now removing the `--rm`option from the run command in the tests to see if it solves the problem.
