### ISSUE TITLE
Misleading error is thrown when phpqa generate command don't receive a target directory

### ISSUE THREAD

**Issue by brunoric** [herdphp/docker-phpqa#45]
As mentioned by @benharold in a [pull request at the phpcommunity/phptestfest.org](https://github.com/phpcommunity/phptestfest.org/pull/43), when the generate command doesn't receive any target directory it throws a misleading error.

**Comment by jpjoao** [comment]
No new tests for those scenarios were created. Can we have some to prevent future regressions?
