### ISSUE TITLE
Different results with make and phpqa

### ISSUE THREAD

**Issue by zf2timo** [herdphp/docker-phpqa#54]
I cloned the `phptestfest-php-src` and executed some tests with the phpqa tool. 
When I execute the test from the security folder almost all tests are fail.

Here is the log from my [console](https://gist.github.com/zf2timo/48f768a00f73e048ed07bb1f0033eb02).
I am not sure why this happens, but it only occurs within the docker env. If I execute the test on a Host machine with `make` there is only one failure.

**Comment by brunoric** [comment]
Hi @zf2timo to have same results locally and using the docker images you will need to make sure that the compiled PHP is exactly the same, including the extensions enabled and other configurations.

Thakns.
