### ISSUE TITLE
Add documentation about PHPT

### ISSUE THREAD

**Issue by brunoric** [herdphp/docker-phpqa#8]
Improve documentation, adding a session about how to write PHPT and how to send the created tests to PHP QA.

**Comment by jpjoao** [comment]
Should we have documentation on this here or help building better documentation on other places and reference them here?

**Comment by ivanrosolen** [comment]
Starting a How To PHPT doc.

About the "send the created tests to PHP QA." I'm not sure, but think that a PR to the right branch is a good way.

Does anyone knows if there is a "right way"?

**Comment by brunoric** [comment]
Just merged your PR @ivanrosolen. Great! And about how to send the tests... well, there is an entry in the QA Wiki about this:

> The next step is to get someone to review it. If it's short you can paste it into a note and send it to php-qa@lists.php.net. If the test is a bit too long for that then put it somewhere were people can download it (pastebin is sometimes used). Appending tests to notes as files doesn't work well - so please don't do that. Your note to php-qa@lists.php.net should say what level of PHP you have tested it on and what platform(s) you've run it on. Someone from the PHP QA group will review your test and reply to you. They may ask for some changes or suggest better ways to do things, or they may commit it to PHP.
http://qa.php.net/write-test.php#whattodo

Dunno if this is outdated or not. I will send an email asking about it.

**Comment by brunoric** [comment]
They also mention about doing Pull Request for the repositories listed [here](https://qa.php.net/pulls/).

**Comment by jpjoao** [comment]
Any answer from the guys on QA?

Also, I was thinking on moving the documentation to the wiki in github to make it easier to update it. What you think?

**Comment by brunoric** [comment]
I think using the Wiki is a good idea. Regarding QA list, no response yet, but I assume that gists/pastebins/snippets with PHPT to the qa list or PRs to the specific extensions repositories will work.

**Comment by rogeriopradoj** [comment]
+1 for moving the documentation to [Wiki](https://github.com/herdphp/docker-phpqa/wiki).

**Comment by brunoric** [comment]
Closing this one. Although we should keep the docs updated this is is ok to be closed since we already added some documentation. =)
